### ISSUE TITLE
[JOSS Review] Add "interesting" doc examples to the examples folder

### ISSUE THREAD

**Issue by sea-bass** [auctus-team/pycapacity#4]
The docs have lots of great examples of PyCapacity integrating with Peter Corke's robotics toolbox, Pinocchio, etc. However, these standalone Python files are not available in the repo itself -- you have to copy-paste them from the docs. The `examples` folder only has simple randomized robot examples.

Please consider adding these doc examples in as "official" examples so it's easy to run them directly without having to make a new file and copy the docs contents. You can also have the docs point to the path of these example files, for example `python3 examples/robotics_toolbox_example.py`

Totally understandable if users have to `pip install` a few extra dependencies, simply mark this in the comments for each example as appropriate. You could also share those anaconda / pip configs in the examples folder for the users to easily set up.

https://github.com/openjournals/joss-reviews/issues/5670

**Comment by askuric** [comment]
Hey @sea-bass,

Sorry for the delay, I've not had much time to spend on pycapacity. 
Thank's for the suggestion, its a good idea. I did not do it at the start because most of these libraries require adding more dependencies.  But I've took your suggestion and I've documented the examples a bit more than before and pointed to the docs page to find the full tutorial, so it should not be too hard to use.

So, I've added some more examples in the examples folder and separated them in the notebooks and scripts. 
The notebooks are really cool, as they are interactive and you can see the polytopes and ellipsoids visualised as you move the robot :D
I've also added the links in the docs to direct people to the examples.

**Comment by sea-bass** [comment]
Thank you!
